name: pemmob2
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # SQLite
  sqflite: ^2.4.0 # Memastikan Anda menggunakan versi terbaru yang stabil
  path_provider: ^2.1.4 # Memastikan kompatibilitas dengan versi terbaru

  # Animasi dan UI
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.1.0
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  flutter_gradient_animation_text: ^1.0.2
  buttons_tabbar: ^1.3.14
  fl_chart: ^0.69.0

  #image
  image: ^4.3.0
  image_picker: ^1.1.2

  # Keamanan
  crypto: ^3.0.6
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.jpeg # Tambahkan jalur aset di sini
